services:
  pocketbase:
    image: pocketbase/pocketbase:latest
    container_name: erbolamm_pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_hooks:/pb_hooks
    command: serve --http=0.0.0.0:8090 --dir=/pb_data --hooks-dir=/pb_hooks
